name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: build release
        run: cargo build --release

      - name: github release
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/esp.exe
          generate_release_notes: true